### ISSUE TITLE
Wrong end time

### ISSUE THREAD

**Issue by Pulpyyyy** [aneeshd/schedule_state#164]
Hello and thanks for this integration i just discovered.

I made a small configuration : 
```
- platform: schedule_state
  name: Consignes repos
  refresh: 0:15:00
  default_state: "{{ states('input_number.consigne_eco')}}"
  events:
    - start: "7:00"
      end: "8:30"
      state: "{{states('input_number.consigne_confort')}}"
      condition:
        - condition: state
          entity_id: binary_sensor.jour_semaine
          state: "on"
    - start: "19:30"
      end: "22:00"
      state: "{{states('input_number.consigne_confort')}}"
      condition:
        - condition: state
          entity_id: binary_sensor.jour_semaine
          state: "on"
    - start: "7:30"
      end: "9:30"
      state: "{{states('input_number.consigne_confort')}}"
      condition:
        condition: time
        weekday:
          - sat
    - start: "20:00"
      end: "22:30"
      state: "{{states('input_number.consigne_confort')}}"
      condition:
        condition: time
        weekday:
          - sat
    - start: "8:30"
      end: "10:00"
      state: "{{states('input_number.consigne_confort')}}"
      condition:
        condition: time
        weekday:
          - sun
    - start: "20:00"
      end: "22:30"
      state: "{{states('input_number.consigne_confort')}}"
      condition:
        condition: time
        weekday:
          - sat
          - sun
```
Sensor is created as is : 
![image](https://github.com/aneeshd/schedule_state/assets/32004297/821054b2-45f3-4a22-90d6-2faf836b1b48)

But as next change should occurs tomorrow (it sunday 11:00 PM atm), i was expecting end time should have monday start time (and not current day end time)

I'm wrong ?

Regards
