### ISSUE TITLE
Setting attributes without changing state or times

### ISSUE THREAD

**Issue by cwrau** [aneeshd/schedule_state#187]
## Version of the schedule_state component

0.19.0

## Configuration

```yaml
default_state: 18
events:
- state: 15
  start: 10:00
  end: 15:00
- state: 20
  start: 15:00
  end: 20:00
- condition:
    - condition: state
      entity_id: binary_sensor.wohnzimmer_fenster
      state: "on"
  window: "open"
```

## Describe the bug

When it's `13:00` and the window is `open`, the state is `18` and starts from `00:00` to `23:59` instead of the expected `15` from `10:00` to `15:00`. Also, the `next_state` is `18` instead of the expected `20`.

**Comment by aneeshd** [comment]
Start and end times need to be quoted. This is why it's not working as you expect. Added note in README

**Comment by cwrau** [comment]
> Start and end times need to be quoted. This is why it's not working as you expect. Added note in README

Actually you don't, `10:00` is just valid as a string.

And even if quoted, which it actually is in my config, it still doesn't work

**Comment by aneeshd** [comment]
I don’t know what to tell you. I have created a unit test that works when the times are quoted and fails when they are not. I am using the same config you provided.

**Comment by aneeshd** [comment]
Please include log files, following the instructions in the documentation. That might help debug the issue. On Dec 17, 2023, at 15:05, Chris Werner Rau ***@***.***> wrote:﻿

Start and end times need to be quoted. This is why it's not working as you expect. Added note in README

Actually you don't, 10:00 is just valid as a string.
And even if quoted, which it actually is in my config, it still doesn't work

**Comment by cwrau** [comment]
This is my `test.yaml`;

```yaml
platform: schedule_state
name: schedule test
refresh: "00:30:00"
default_state: 18
minutes_to_refresh_on_error: 1
extra_attributes:
  unit_of_measurement: "°C"
  state_class: measurement
  window: "closed"
events:
  - state: 15
    start: "10:00"
    end: "15:00"
  - state: 20
    start: "15:00"
    end: "20:00"
  - condition:
      - condition: state
        entity_id: binary_sensor.wohnzimmer_fenster
        state: "on"
    window: "open"
```

This is the state with the window closed;

```yaml
icon: mdi:calendar-check
friendly_name: schedule test
states:
  - "15"
  - "20"
  - "18"
next_state: "20"
start: "10:00:00"
end: "15:00:00"
friendly_start: "10:00:00"
friendly_end: "15:00:00"
errors: []
unit_of_measurement: °C
state_class: measurement
window: closed
```

This is the state with the window open;

```yaml
icon: mdi:calendar-check
friendly_name: schedule test
states:
  - "15"
  - "20"
  - "18"
next_state: "18"
start: "00:00:00"
end: "23:59:59.999999"
friendly_start: "00:00:00"
friendly_end: midnight
errors: []
unit_of_measurement: °C
state_class: measurement
window: open
```

There are no logs for this, even with `debug` 😅

**Comment by aneeshd** [comment]
What are you using to get this info:

> This is the state with the window closed;
> 
> icon: mdi:calendar-check
> friendly_name: schedule test

(etc)
???

schedule_state creates INFO logs in the HA log by default, so you should at least see things like:

INFO     custom_components.schedule_state.sensor:sensor.py:754 schedule test:
{'15': (),
 '18': [datetime.time(0, 0),datetime.time(23, 59, 59, 999999)),
 '20': ()}
{'state_class': {'measurement': [datetime.time(0, 0),datetime.time(23, 59, 59, 999999))},
 'unit_of_measurement': {'°C': [datetime.time(0, 0),datetime.time(23, 59, 59, 999999))},
 'window': {'closed': (),
            'open': [datetime.time(0, 0),datetime.time(23, 59, 59, 999999))}}

For info on HA logs: https://www.home-assistant.io/integrations/system_log/ <https://www.home-assistant.io/integrations/system_log/>

To enable schedule_state DEBUG logs: https://github.com/aneeshd/schedule_state?tab=readme-ov-file#on-a-real-ha-instance <https://github.com/aneeshd/schedule_state?tab=readme-ov-file#on-a-real-ha-instance>

I need at least the INFO logs, preferably the DEBUG logs.

**Comment by cwrau** [comment]
> What are you using to get this info:
> 
> > This is the state with the window closed;
> > 
> > icon: mdi:calendar-check
> > friendly_name: schedule test
> 
> (etc)
> ???

That's the `/developer-tools/state` page. 


> schedule_state creates INFO logs in the HA log by default, so you should at least see things like:
> 
> INFO     custom_components.schedule_state.sensor:sensor.py:754 schedule test:
> {'15': (),
>  '18': [datetime.time(0, 0),datetime.time(23, 59, 59, 999999)),
>  '20': ()}
> {'state_class': {'measurement': [datetime.time(0, 0),datetime.time(23, 59, 59, 999999))},
>  'unit_of_measurement': {'°C': [datetime.time(0, 0),datetime.time(23, 59, 59, 999999))},
>  'window': {'closed': (),
>             'open': [datetime.time(0, 0),datetime.time(23, 59, 59, 999999))}}
> 
> For info on HA logs: https://www.home-assistant.io/integrations/system_log/ <https://www.home-assistant.io/integrations/system_log/>
> 
> To enable schedule_state DEBUG logs: https://github.com/aneeshd/schedule_state?tab=readme-ov-file#on-a-real-ha-instance <https://github.com/aneeshd/schedule_state?tab=readme-ov-file#on-a-real-ha-instance>
> 
> I need at least the INFO logs, preferably the DEBUG logs.

I have the following in my `configuration.yaml`;

```yaml
logger:
  default: warn
  logs:
    custom_components.schedule_state: debug
```

And I'm not getting any logs from this integration 😅

I even restarted HA afterwards.

**Comment by aneeshd** [comment]
I took a closer look at your config.

This event:

```
  - condition:
      - condition: state
        entity_id: binary_sensor.wohnzimmer_fenster
        state: "on"
    window: "open"
```

Has no start/end times - so it is the whole day. Which means, whenever your window is open, everything reverts to the default state. This matches the INFO log I see. 

I don't know why you don't get any log messages, probably you have disabled logs by some other means.

Overall, I am not seeing a bug here. Maybe a clarification is needed in the documentation?

Thanks for the `/developer-tools/state` pointer. I did not know about that view.
