### ISSUE TITLE
Override end event

### ISSUE THREAD

**Issue by hilburn** [aneeshd/schedule_state#256]
I'm trying to use this to control heating and it's working great - except for when I'm trying to run an override heating boost. 

```
service: schedule_state.set_override  
target:  
  entity_id: sensor.heating_schedule  
data:  
  id: boosting  
  state: boost  
  duration: " {{ states('input_number.boost_length') }} "
```

There doesn't seem to be an event fired when the override ends which means the automation watching the state of the schedule for changes never goes back to the initial temperatures
I'm currently getting around this with an override and a template that returns true between button pressed and button pressed + boost time, but this feels a bit hacky, and would be great to be able to avoid having to do this in the future
