### ISSUE TITLE
Icon based on schedule value, rather than current event

### ISSUE THREAD

**Issue by hilburn** [aneeshd/schedule_state#350]
## Version of the schedule_state component
0.19.4

## Configuration

```yaml

events:
  - start: "22:00"
    end: "6:30"
    state: '{{states("input_number.night_heat")}}'
    icon: mdi:weather-night
    allow_wrap: True
  - start: "6:30"
    end: "8:00"
    state: '{{states("input_number.day_heat")}}'
    icon: mdi:sun-clock
    condition: &workday
      condition: state
      entity_id: binary_sensor.workday_with_override
      state: 'on'

```

## Describe the bug
In the above, if night_heat == day_heat, the icon shown will be `mdi:sun-clock` even if between the hours of 10pm and 6.30am - if it varies even slightly, the night icon will show correctly
It does work if I set the states to be e.g. "night" and "day" and instead store the input_number as an attribute, but I'd rather not do that as it breaks graphing the state

## Debug log

N/A

```
