### ISSUE TITLE
Override's "extra_attributes" not being applied properly

### ISSUE THREAD

**Issue by hilburn** [aneeshd/schedule_state#356]
## Version of the schedule_state component

0.19.4

## Configuration

schedule_state Sensor

```yaml

- platform: schedule_state
  name: base_heating_schedule
  default_state: eco
  icon: mdi:leaf
  extra_attributes:
    icon_color: green
    override_temperature: 0
  events:
    - start: "21:00"
      end: "6:30"
      state: custom
      icon: mdi:weather-night
      allow_wrap: True
      icon_color: grey
      override_temperature: 13

```

Action

```yaml
action: schedule_state.set_override
target:
  entity_id: sensor.base_heating_schedule
data:
  id: custom
  state: custom
  duration: 10
  icon: mdi:home-thermometer
  extra_attributes:
    override_temperature: 15
    icon_color: blue
```

## Describe the bug

Extra attributes applied in an override action are not applied to the sensor properly

As a demo - here is a card I am putting together to show the interpreted state of the schedule_state sensor above, with the "inherent" event working fine, but reverting to default extra_attributes when the override is applied

```yaml
type: custom:mushroom-template-card
primary: "{{ state_attr(entity,'friendly_name') }}"
secondary: >-
  {% set entity = "sensor.base_heating_schedule" %}
  {% set mode = states(entity) %}
  Heating Mode: {{ 'Custom: %s°C' % state_attr(entity, 'override_temperature')
  if mode == "custom" else mode | capitalize }}
icon: "{{ state_attr(entity,'icon') }}"
icon_color: "{{ state_attr(entity,'icon_color') }}"
entity: sensor.base_heating_schedule
badge_icon: "{{ state_attr(entity,'icon') }}"
badge_color: "{{ state_attr(entity,'icon_color') }}"
tap_action:
  action: more-info
hold_action:
  action: none
double_tap_action:
  action: none

```

Event state output - "Night" mode displays fine
![image](https://github.com/user-attachments/assets/21758e71-d4b8-419c-91a0-bd44ca68371f)

Action override output - icon changes, but `icon_color` and `override_temperaure` return default values
![image](https://github.com/user-attachments/assets/af4fc529-1b35-4d69-806c-f5c250e86bb5)

This also bears out in the Developer Tools > State tab

## Debug log

```text

2024-10-29 21:04:23.398 INFO (MainThread) [custom_components.schedule_state.sensor] base_heating_schedule: override to custom for id=custom s=None e=None d=10 ea={'override_temperature': 15, 'icon_color': 'blue'}
2024-10-29 21:04:23.401 INFO (MainThread) [custom_components.schedule_state.sensor] base_heating_schedule:
{'comfort': [datetime.time(6, 30),datetime.time(8, 0)) | [datetime.time(16, 30),datetime.time(20, 0)),
 'custom': [datetime.time(0, 0),datetime.time(6, 30)) | [datetime.time(21, 0),datetime.time(23, 59, 59, 999999)),
 'eco': [datetime.time(8, 0),datetime.time(16, 30)) | [datetime.time(20, 0),datetime.time(21, 0))}
{'icon_color': {'green': [datetime.time(8, 0),datetime.time(16, 30)) | [datetime.time(20, 0),datetime.time(21, 0)) | [datetime.time(21, 4),datetime.time(21, 14)),
                'grey': [datetime.time(0, 0),datetime.time(6, 30)) | [datetime.time(21, 0),datetime.time(21, 4)) | [datetime.time(21, 14),datetime.time(23, 59, 59, 999999)),
                'yellow': [datetime.time(6, 30),datetime.time(8, 0)) | [datetime.time(16, 30),datetime.time(20, 0))},
 'override_temperature': {'0': [datetime.time(6, 30),datetime.time(21, 0)) | [datetime.time(21, 4),datetime.time(21, 14)),
                          '13': [datetime.time(0, 0),datetime.time(6, 30)) | [datetime.time(21, 0),datetime.time(21, 4)) | [datetime.time(21, 14),datetime.time(23, 59, 59, 999999))},

```
