### ISSUE TITLE
Template conditions aren't re-evaluated when entity changes

### ISSUE THREAD

**Issue by wltng** [aneeshd/schedule_state#371]
## Version of the schedule_state component

0.19.5
## Configuration

```yaml
- platform: schedule_state
  name: Test Schedule State, not working
  default_state: "default"
  events:
    - start: 00:00
      end: 23:59
      state: "chicken"
      icon: mdi:food-drumstick
      condition:
        - condition: template
          value_template: "{{ states('input_number.test') | int (0) > 2 }}"
```
```yaml
- platform: schedule_state
  name: Test Schedule State, working but giving errors during HA startup
  default_state: "default"
  events:
    - start: 00:00
      end: 23:59
      state: "chicken"
      icon: mdi:food-drumstick
      condition:
        - condition: numeric_state
          entity_id: input_number.test          
          above: 2
```

When using template conditions, nothing shows up in the logs (just the way I wanted :-)

## Describe the bug
The state doesn't change when the condition templates change. In this case when I change the input_number to >2
If I use state conditions it does work, however I get errors in the logs during startup (as entities aren't available yet.

Using the template conditions, I can select default values, so the logs won't show errors when starting HA because of unavailable entities.

## Debug log

```text
None available when using templates


```
