### ISSUE TITLE
Monthly refresh for energy tariffs

### ISSUE THREAD

**Issue by danieldotnl** [aneeshd/schedule_state#38]
Nice component!
I would like to use this to calculate the correct energy prices. My energy prices change monthly and since I'm not willing to update them manually exactly at midnight at the beginning of the month, I would love to use schedule_state :)
However, I'm not sure if it will work. I guess i can use `start_template` and `end_template` to define the start/end of the month? (btw, ideally I would leave `end` empty, until I add a new tariff).
Do I understand correctly that I need to configure a refresh every minute to then make this work?

Thank you!!

**Comment by danieldotnl** [comment]
Ok, not sure if it is the ideal config, but I can confirm this test works:

```yaml
- platform: schedule_state
    name: Actual gas price
    refresh: "00:01:00"
    default_state: "1.00"
    events:
      - start_template: "2022-08-22T16:55:00+02:00"
        end_template: "2022-08-22T17:00:00+02:00"
        state: "0.25"
      - start_template: "2022-08-22T17:00:00+02:00"
        end_template: "2022-08-22T18:00+02:00"
        state: "0.5"
```
