### ISSUE TITLE
Conditions not working

### ISSUE THREAD

**Issue by TheBestMoshe** [aneeshd/schedule_state#380]
I'm unsure if this is user error or if there is a bug, but should this code work?

```
- platform: schedule_state
  name: Step brightness
  allow_wrap: True
  icon: mdi:circle-half
  events:
    - state: light
    - start: "{{ as_timestamp(state_attr('sun.sun', 'next_setting')) }}"
      end: "{{ as_timestamp(state_attr('sun.sun', 'next_rising')) }}"
      state: dark
      conditions:
        - condition: state
          entity_id:
            - light.first_floor_hallway_light
            - light.second_floor_hallway_light
            - light.step_spots
          state: "off"
```

The start/end time work. During this time, the state is `dark`. 

However, if any of those lights are not `off`, I want the state of this entry to be `light`. 

But it's always `dark` even when a light is off.

Do conditions not work the way I'm trying to use them?
