### ISSUE TITLE
Add support for templates in `state`

### ISSUE THREAD

**Issue by nagyrobi** [aneeshd/schedule_state#44]
**Is your feature request related to a problem? Please describe.**
I'm the author of [Smart heating scheduler for Home Assistant](https://community.home-assistant.io/t/smart-heating-scheduler-for-home-assistant-extra-multi-zones-version/237966) package of automations. It uses a bunch of `input_datetime`, `input_number` and `input_boolean` entities combined with templates to mimic a schedule system for one or more thermostats, accounting for home/away state etc.

Looks like your component could be used to simplify that quite a bit, great work, thank you!

**Describe the solution you'd like**
To simplify automations even more it would be nice to be possible to return the scheduled `state` also based on a template.
Currently we can set up the `events` with `start_template`, `end_template` pointing to `input_datetime` entities, which is great.
It would be great if we could set the `state` too with a template pointing to `input_number` entity.

The use case is very simple: for the time event between start and end, the user wants to set a temperature value. Time periods can be configured via the UI, like:
```
        start_template: "{{ states('input_datetime.heating_weekday_morning_start') }}"
        end_template: "{{ states('input_datetime.heating_weekday_day_start') }}"
```
it would be very useful to also have something like this:
```
        state_template: "{{ states('input_number.heating_temp_morning') }}"
```
So the value of the schedule sensor would correspond to a value of a numeric input sensor editable in the UI, different for each event.
This way, a single automation would be enough to set directly the temperature of the thermostat:
```
trigger:
  - platform: state
    entity_id:
      - sensor.heating_schedule
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.heating
      temperature: "{{ states('sensor.heating_schedule') | float (default=19.0) }}"
```

Note that we need the same possibilty for the `default_state`, something like `default_state_template` - as a fallback corresponding to the `away` mode, when no events would apply (conditions ensuring that in each event).

**Describe alternatives you've considered**
A more complex automation is needed without this, because states can only be static strings, we need an `action` with multiple `choose` and `sequence` sections corresponding with each string predefined in the component.

**Additional context**
N/A
