### ISSUE TITLE
Add settable attributes to the entity

### ISSUE THREAD

**Issue by nagyrobi** [aneeshd/schedule_state#45]
**Is your feature request related to a problem? Please describe.**
Similar to the main `state` of the entity, it would be nice to also have the possibility to add custom attributes to it, which could also be scheduled.

**Describe the solution you'd like**
Something like, for example in case of a fan coil heater:

```
  - platform: schedule_state
    name: "Fan coil heating schedule"
    refresh: "6:00:00"
    default_state: "temp_away"
    attributes: [fan_mode: off, swing_mode: off]    # an optional list with custom attributes and their defaults
    icon: mdi:clock-check-outline
    error_icon: mdi:clock-alert
    minutes_to_refresh_on_error: 5
    events:
      - start: "0:00"
        end: "5:30"
        state: "temp_night"
        fan_mode: "low"
        swing_mode: "off"
        icon: mdi:sleep
      - start: "5:30"
        end: "22:30"
        state: "temp_day"
        fan_mode: "high"
        swing_mode: "off"
        icon: mdi:walk
      - start: "22:30"
        state: "temp_evening"
        fan_mode: "mid"
        swing_mode: "vertical"
```
This could add more flexibility to adjust multiple parameters within the schedule, saving us from having to create complex automations to derive them only from one state value.

Eg. attribute can be easily retrieved with `{{ state_attr('sensor.fan_coil_heating_schedule','fan_mode') }}`.
Automations can be triggered also on attribute changes etc.

And of course it would be lovely if these would support templates for similar reasons as https://github.com/aneeshd/schedule_state/issues/44 (including the defaults).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
