### ISSUE TITLE
Override more than 24 hours

### ISSUE THREAD

**Issue by nagyrobi** [aneeshd/schedule_state#49]
**Is your feature request related to a problem? Please describe.**
I called the `set_override` service with `duration: 2888` which is 2 days and 8 minutes. No error happened, however, the state returned to the one from the corresponding event after 8 minutes. Looks like the 2 days were ignored.

**Describe the solution you'd like**
To set an override for any time interval in the future. Use case is for longer week-ends / holidays etc which may run over a day.

**Describe alternatives you've considered**
None possible afaik.

**Additional context**
N/A

**Comment by aneeshd** [comment]
Hmm, have to think about how to do this. `schedule_state` has no concept of dates. But your use case is a good one.

**Comment by nagyrobi** [comment]
> `schedule_state` has no concept of dates

I see. In that case, it may be too complicated to implement. But as it turns out that events evaluation order is always top-to-bottom, and all are evaluated, thus if multiple events match the settings it's always the last one that "wins", we already have another overriding method with end time:

Have an `input_boolean.override_switch` to control the override state on/off, and have an `input_datetime.heating_override_until` (with date and time) to control the deadline any time in the future.

Adding this as the _last_ event in the events config list:

```yaml
      - state: away_mode
        condition:
          - condition: state
            entity_id: input_boolean.override_switch
            state: 'on' 
```
All we have to do is to turn the switch off at deadline, with a simple automation:
```yaml
- id: override_disable_overide_when_deadline
  alias: Override disable when deadline reached
  trigger:
    - platform: time
      at: input_datetime.heating_override_until
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: 'input_boolean.override_switch'
```
Additional benefit is that `input_boolean` state is remembered between HA restarts, so after boot, `schedule_state` will re-evaluate the events and as long as `input_boolean.override_switch` is still ON, it will keep the override.
