### ISSUE TITLE
Events processing order and final result

### ISSUE THREAD

**Issue by nagyrobi** [aneeshd/schedule_state#50]
Given the configuration below:
```yaml
  - platform: schedule_state
    name: Huba fűtés
    refresh: "6:00:00"
    default_state: futes_hiba
    icon: mdi:web-clock
    error_icon: mdi:clock-alert
    minutes_to_refresh_on_error: 5
    events:
# WEEKDAYS
      - state: futes_ejszaka
        icon: mdi:clock-time-eleven-outline
        end_template: "{{ states('input_datetime.heating_weekday_morning_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'off' 
      - state: futes_reggel
        icon: mdi:clock-time-seven-outline
        start_template: "{{ states('input_datetime.heating_weekday_morning_start') }}"
        end_template: "{{ states('input_datetime.heating_weekday_day_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'off' 
      - state: futes_napkozben
        icon: mdi:clock-time-one-outline
        start_template: "{{ states('input_datetime.heating_weekday_day_start') }}"
        end_template: "{{ states('input_datetime.heating_weekday_evening_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'off' 
      - state: futes_este
        icon: mdi:clock-time-four-outline
        start_template: "{{ states('input_datetime.heating_weekday_evening_start') }}"
        end_template: "{{ states('input_datetime.heating_weekday_night_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'off' 
      - state: futes_ejszaka
        icon: mdi:clock-time-eleven-outline
        start_template: "{{ states('input_datetime.heating_weekday_night_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'off' 

# WEEKENDS
      - state: futes_ejszaka
        icon: mdi:clock-time-eleven-outline
        end_template: "{{ states('input_datetime.heating_weekend_morning_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'on' 
      - state: futes_reggel
        icon: mdi:clock-time-seven-outline
        start_template: "{{ states('input_datetime.heating_weekend_morning_start') }}"
        end_template: "{{ states('input_datetime.heating_weekend_day_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'on' 
      - state: futes_napkozben
        icon: mdi:clock-time-one-outline
        start_template: "{{ states('input_datetime.heating_weekend_day_start') }}"
        end_template: "{{ states('input_datetime.heating_weekend_evening_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'on' 
      - state: futes_este
        icon: mdi:clock-time-four-outline
        start_template: "{{ states('input_datetime.heating_weekend_evening_start') }}"
        end_template: "{{ states('input_datetime.heating_weekend_night_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'on' 
      - state: futes_ejszaka
        icon: mdi:clock-time-eleven-outline
        start_template: "{{ states('input_datetime.heating_weekend_night_start') }}"
        condition:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'on' 

# AWAY
      - state: futes_tavol
        icon: mdi:close-circle-outline
        condition:
          - condition: state
            entity_id: binary_sensor.family_at_home
            state: 'off' 
```

I noticed that all events are evaluated, and the _last one matching_ always wins, _even if there are more matching_.
(I moved the event for _AWAY_ to the top of the config, then it had no effect, looks like it has to be the last)
Based on this, with the config above I can implement a kind of event-based override, which has no `start` and `end` times (=all day), but has a condition relying on an external sensor or input.

Is it safe to use it like this? (would be nice like a firewall, processing rules from top to bottom, but last matching wins :) )

If not, I could of course change the condition to
```yaml
        condition:
          condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.orverride_freeday
            state: 'on' 
          - condition: state
            entity_id: binary_sensor.family_at_home
            state: 'on' 
```
for each event, but that makes the config pretty complicated, not talking about adding more such...
