### ISSUE TITLE
Add support for `unit_of_measurement` and `state_class`

### ISSUE THREAD

**Issue by nagyrobi** [aneeshd/schedule_state#56]
**Is your feature request related to a problem? Please describe.**
Having numeric values for the state implies that the sensor values can be displayed graphically.
Currently the state history is only displayed on a single dimensional bar.
However, if we use it to [schedule target temperature values](https://github.com/aneeshd/schedule_state/issues/44) it would be useful to display the state history as a temperature graph. To achieve this, we would need to define `state_class: measurement` for the sensor, and optionally set `unit_of_measurement: "°C"` too.

**Describe the solution you'd like**
Add support for `unit_of_measurement` and `state_class` attributes for the sensor, configurable for example like this:
```yaml
unit_of_measurement: "°C"
state_class: measurement
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aneeshd** [comment]
I believe this can now be done like this:

```
  - platform: schedule_state
    name: "Temperature schedule"
    extra_attributes:
      unit_of_measurement: "°C"
      state_class: measurement
```
