### ISSUE TITLE
Don't update state and attributes if calculated value doesn't change

### ISSUE THREAD

**Issue by nagyrobi** [aneeshd/schedule_state#63]
**Is your feature request related to a problem? Please describe.**
The configuration is [the same as here](https://github.com/aneeshd/schedule_state/issues/61#issue-1393563454), what happens is, that if templates belonging to other events change, the current event sends and update too - to the same value.

For example if we're in any event during the day (eg. `Hétköznap éjszaka`), the main state is the value reported by `input_number.heating_6_temp_night`. However, when I adjust `input_number.heating_6_temp_override` (with condition not passing), I notice that the sensor gets a new state update, with the same, correct value of `input_number.heating_6_temp_night`.

**Describe the solution you'd like**
This is disturbing when using to schedule the target temperature of an air conditioner via IR commands with an IR blaster. The IR commands (with the same temperature) are re-sent every time I adjust parameters in templates outside the current event. The AC unit in the room beeps at each IR command it receives - this should be avoided.

**Describe alternatives you've considered**
As a workaround I added an `if` sequence to the action of the climate control automation:
```yaml
- id: heating_6_sched_to_climate
  alias: Thermo heating_6
  trigger:
  - platform: state
    entity_id: 'sensor.heating_6_schedule'
  action:
  - if:
      - condition: template
        value_template: "{{ state_attr('climate.room_ac','temperature') | float (default=19.0) != states('sensor.heating_6_schedule') | float (default=19.0) }}"
    then:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.room_ac
          temperature: "{{ states('sensor.heating_6_schedule') | float (default=19.0) }}"
```

**Additional context**
Maybe it would be simply enough to add a similar check in the `update` function of the component to only return data if the value differs from the previous state (put the state before calculation into a temp variable, do the calc, and then only push it out if it differs from the temp var)...?
I guess attributes could be treated similarly, I mean, the update/calculation still has to be ran at every template change, only returning the results should be filtered individually.
Additional benefit, if the schedule has events coming after another with the same states or some attributes, still don't send updates.

One exception: when recalculate is deliberately triggered by an external service call - then yes, force updates even if values will be the same for state and attributes.
