### ISSUE TITLE
Setup failed for custom integration schedule_state: No setup or config entry setup function defined.

### ISSUE THREAD

**Issue by Reynders1** [aneeshd/schedule_state#68]
## Version of the schedule_state component
8f4000b

## Configuration

```
- platform: schedule_state
    name: Schedule salon
    refresh: "6:00:00"
    default_state: default
    icon: mdi:calendar-check
    error_icon: mdi:calendar-alert
    minutes_to_refresh_on_error: 5
    events:
      - start: "0:00"
        end: "6:30"
        state: night
        icon: mdi:weather-night
      - start: "6:30"
        end: "7:30"
        state: boost
        icon: mdi:thermometer-chevron-up
      - start: "7:30"
        end: "23:00"
        state: day
        icon: mdi:sun-thermometer
      - start: "23:00"
        state: night
        icon: mdi:weather-night
      - state: away
        condition:
          - condition: state
            entity_id: zone.home
            state: '0'
  - platform: schedule_state
    name: Schedule cuisine
    refresh: "6:00:00"
    default_state: default
    icon: mdi:calendar-check
    error_icon: mdi:calendar-alert
    minutes_to_refresh_on_error: 5
    events:
      - start: "0:00"
        end: "7:30"
        state: night
        icon: mdi:weather-night
      - start: "7:30"
        end: "23:00"
        state: day
        icon: mdi:sun-thermometer
      - start: "22:00"
        state: night
        icon: mdi:weather-night
      - state: away
        condition:
          - condition: state
            entity_id: zone.home
            state: '0'
  - platform: schedule_state
    name: Schedule SaM
    refresh: "6:00:00"
    default_state: default
    icon: mdi:calendar-check
    error_icon: mdi:calendar-alert
    minutes_to_refresh_on_error: 5
    events:
      - start: "0:00"
        end: "7:30"
        state: night
        icon: mdi:weather-night
      - start: "7:30"
        end: "23:00"
        state: day
        icon: mdi:sun-thermometer
      - start: "22:00"
        state: night
        icon: mdi:weather-night
      - state: away
        condition:
          - condition: state
            entity_id: zone.home
            state: '0'
  - platform: schedule_state
    name: Schedule SdB
    refresh: "6:00:00"
    default_state: default
    icon: mdi:calendar-check
    error_icon: mdi:calendar-alert
    minutes_to_refresh_on_error: 5
    events:
      - start: "0:00"
        end: "6:30"
        state: night
        icon: mdi:weather-night
      - start: "6:30"
        end: "7:30"
        state: boost
        icon: mdi:thermometer-chevron-up
      - start: "7:30"
        end: "23:00"
        state: day
        icon: mdi:sun-thermometer
      - start: "23:00"
        state: night
        icon: mdi:weather-night
      - state: away
        condition:
          - condition: state
            entity_id: zone.home
            state: '0'
```

Add your logs here.

1. This error originated from a custom integration.
Logger: custom_components.schedule_state.sensor
Source: custom_components/schedule_state/sensor.py:240 
Integration: schedule_state (documentation, issues) 
First occurred: 11:01:30 (4 occurrences) 
Last logged: 11:01:30

Schedule salon: away: error evaluating condition - skipping, will try again in 5 minutes
Schedule cuisine: away: error evaluating condition - skipping, will try again in 5 minutes
Schedule SaM: away: error evaluating condition - skipping, will try again in 5 minutes
Schedule SdB: away: error evaluating condition - skipping, will try again in 5 minutes

2. Logger: homeassistant.setup
Source: setup.py:230 
First occurred: 11:01:30 (1 occurrences) 
Last logged: 11:01:30

Setup failed for custom integration schedule_state: No setup or config entry setup function defined.

## Describe the bug
Every time I restart HA (recently updated to 2022.10.5, but the issue existed already with 2022.10.4) the below 2 error are reported.

## Debug log

```text

Add your logs here.

```
