### ISSUE TITLE
icon set via set_override not removed if override is removed or cleared

### ISSUE THREAD

**Issue by diplix** [aneeshd/schedule_state#75]
## Version of the schedule_state component
latest

## Describe the bug
i can set an icon via 

```
          - service: schedule_state.set_override
            data:
              state: xxx
              id: xxx
              extra_attributes:
                status: Manuell
              duration: 240
              icon: mdi:cursor-pointer
            target:
              entity_id: sensor.xxx
```

but the icon is not removed by any of theses servicecalls
* `schedule_state.remove_override`
* `schedule_state.clear_overrides`
* `schedule_state.recalculate`
