### ISSUE TITLE
On/Off states turn to True/False

### ISSUE THREAD

**Issue by janrg** [aneeshd/schedule_state#76]
## Configuration

```yaml

- platform: schedule_state
  name: Motion Controlled Lights Parameters
  refresh: "6:00:00"
  default_state: on
  extra_attributes:
    color_temp_kelvin: 2700
    brightness_pct: 100
  events:
    - end: "07:00"
      brightness_pct: 1
      color_temp_kelvin: 1800
    - start: "00:30"
      end: "06:00"
      state: off
    - start: "07:00"
      end: "19:30"
    - start: "19:30"
      brightness_pct: 30
      color_temp_kelvin: 1800

```

## Describe the bug
If the states I use for my schedule are `on` and `off`, they are turned instead into `True` and `False`.

From the given config I get State: `True` and attributes:

```yaml
states: False, True
start: 06:00:00
end: 00:30:00
friendly_start: 06:00:00
friendly_end: 00:30:00
errors: 
color_temp_kelvin: 1800
brightness_pct: 30
icon: mdi:calendar-check
friendly_name: Motion Controlled Lights Parameters
```
